### ISSUE TITLE
Chimneys not working when stacked past 4

### ISSUE THREAD

**Issue by vizthex123** [elseytd/TheAurorian#18]
I've set it to 1.0 speed and 5 max, but tested it and found the furnace stops working if 5 chimneys are placed on it.

It's got to have 4 or less to work. Kind of weird.

**Comment by shiroroku** [comment]
did some testing, this is because setting the speed to 1.0 will cause the burn time of items to equate to 0, meaning they wont be cooked. i'll change the max speed value to 0.99.

heres some pseudocode on how the math works:
to calculate chimney speed: `(chimneys on furnace / maximum chimneys) * speed`  
to calculate an items burntime: `burntime - burntime * chimney speed`

**Comment by shiroroku** [comment]
https://github.com/elseytd/TheAurorian/commit/19a1601ac17bd0fe0930ae8c25625fcf197e203d

**Comment by vizthex123** [comment]
Ah ok, hope it gets fixed in the next update then.
