### ISSUE TITLE
Crash on server with spectral armor (Possibly only with Steve's Bizarre Adventure)

### ISSUE THREAD

**Issue by Hydraheads** [elseytd/TheAurorian#25]
**Describe the bug**
Spectral Armor crashes my server when somebody uses it.

**To Reproduce**
Steps to reproduce the bug:
According to the person using it, it was working fine before, but I assume that person just didn't have effects to cleanse before as they thought the armor just had a dodge effect or something.
1. Have Spectral Armor activate its ability on a server
2. Crash

**Versions/Environtment**

- theaurorian-1.12.2-release-jan1121.jar
- Jojovein Modpack

**If you have a Crash Log**
[crash-2021-01-20_17.43.17-server.txt](https://github.com/elseytd/TheAurorian/files/5844304/crash-2021-01-20_17.43.17-server.txt)

**Comment by Hydraheads** [comment]
Actually, this might be a compatibility bug, because the crash seems to be linked to the damage reflection of stands at a glance....

**Comment by shiroroku** [comment]
https://github.com/elseytd/TheAurorian/commit/1cf250285666886ccaa96ed9e2e1637ba5ab2b7a
this should fix it. i was using a client only function `Potion.isBeneficial()` on server side. "didn't have effects to cleanse" is true because the client only code was called when the player has any potion effects.
